apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
   matchLabels:
     app: client
  template: 
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: quanological/client
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
